# Generated by Django 6.0.5 on 2026-05-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliverys", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="title",
            new_name="delv_name",
        ),
    ]
