# Generated by Django 6.0.5 on 2026-05-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliverys", "0002_rename_title_delivery_delv_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="delv_name",
            new_name="title",
        ),
    ]
